includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-simple.yaml

variables:
  main: "."
  binary_name: git-lfs-transfer
  description: "Server-side implementation of the Git LFS pure-SSH protocol"
  github_url: "https://github.com/charmbracelet/git-lfs-transfer"
  maintainer: "Ayman Bagabas <ayman@charm.sh>"
  brew_commit_author_name: "Ayman Bagabas"
  brew_commit_author_email: "ayman@charm.sh"

# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
